### ISSUE TITLE
Plugin does not work with Cider from Microsoft Store

### ISSUE THREAD

**Issue by joshrsmith** [DecibillyJoel/Cider-Plugin-Set-Windows-Audio-Device#1]
If you have Cider installed via Microsoft Store, then the path that is used in index.js to the batch file is something like `AppData\Roaming\Cider\Plugins\setaudiodevice\fixAudioRender.bat`  

But you need it to be something like `AppData\Local\Packages\27554FireDevElijahKlauman.CiderAlpha_270bejk4xgzqp\LocalCache\Roaming\Cider\plugins\setaudiodevice\fixAudioRender.bat`

I have no idea the right (generic) way to fix this.
I was able to fix it locally by using a hard coded path instead of a dynamic path.

**Comment by DecibillyJoel** [comment]
Yeah, I'm not sure either off the top of my head. Later today I'll take a look at the way Cider determines the location of the plugins folder

**Comment by DecibillyJoel** [comment]
Just pushed a fix for this, although I can't test it because my MS store Cider is using the regular AppData path for whatever reason. if you could test this I would appreciate it
